-- Mitesh Real Estate Solution — Supabase schema
-- Run this in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- Safe to re-run: it drops and recreates the two tables.

-- ---------------------------------------------------------------- enquiries
drop table if exists public.enquiries cascade;

create table public.enquiries (
  id          bigint generated always as identity primary key,
  ref         text        not null unique,
  name        text        not null,
  email       text        not null,
  phone       text        not null,
  property_id text,
  location    text,
  budget      text,
  message     text,
  handled     boolean     not null default false,
  created_at  timestamptz not null default now()
);

create index enquiries_created_at_idx on public.enquiries (created_at desc);
create index enquiries_property_id_idx on public.enquiries (property_id);

alter table public.enquiries enable row level security;

-- Anyone (the website, using the publishable key) may submit a lead...
create policy "anon can submit enquiries"
  on public.enquiries for insert to anon with check (true);

-- ...but nobody anonymous can read them back. Use the dashboard or a
-- service_role key on your server to view leads.
revoke select on public.enquiries from anon;

-- ---------------------------------------------------------------- properties
drop table if exists public.properties cascade;

create table public.properties (
  id           text primary key,
  title        text    not null,
  location     text    not null,
  price        bigint,
  type         text    not null,
  area         integer not null default 0,
  size_label   text,
  bedrooms     integer not null default 0,
  bathrooms    integer not null default 0,
  status       text    not null default 'Available',
  featured     boolean not null default false,
  art          text    not null default 'plot',
  rate         integer,
  rera         text,
  transaction  text,
  facing       text,
  description  text,
  amenities    jsonb   not null default '[]'::jsonb,
  images       jsonb,
  sort_order   integer not null default 0,
  published    boolean not null default true,
  updated_at   timestamptz not null default now()
);

create index properties_type_idx on public.properties (type);
create index properties_location_idx on public.properties (location);

alter table public.properties enable row level security;

-- The website reads published listings with the publishable key.
create policy "anon can read published properties"
  on public.properties for select to anon using (published);

-- Writes are dashboard / service_role only — no anon policy is defined.

-- ---------------------------------------------------------------- seed
insert into public.properties
  (id, title, location, price, type, area, size_label, bedrooms, bathrooms,
   status, featured, art, rate, rera, transaction, facing, description,
   amenities, images, sort_order)
values
  ('MRS-201', 'Crescent by Emerald Select', 'Mayakhedi (AB Bypass), Indore', null, 'Residential Plot', 2400, '1,500 – 2,400 sq ft', 0, 0, 'Available', true, 'plot', null, 'P-IND-25-5789', null, null, '''Live the precious'' — a plotted community with a distinctive architectural identity, by Emerald Select at Mayakhedi on the AB Bypass. Premium residential plots of 1,500–2,400 sq ft in a landscaped, amenity-rich layout.', '["Eco gym", "Cricket pitch", "Club house access", "Water fountain", "Gazebo", "Tennis court", "Open sitting area"]'::jsonb, null, 0),
  ('MRS-202', 'Emerald Gateway', 'Sula Khedi, Indore', null, 'Residential Plot', 2000, '1,000 – 2,000 sq ft', 0, 0, 'Available', true, 'plot', null, 'P-SWR-24-4573', null, null, '''A secure foundation for personal living spaces'' — premium residential plots of 1,000–2,000 sq ft at Sula Khedi, entered through a landmark illuminated gateway with a landscaped arrival plaza.', '["Landmark gated entrance", "Landscaped arrival plaza", "Street-lit internal roads", "Secured boundary with barrier entry"]'::jsonb, null, 1),
  ('MRS-203', 'Emerald Aashray', 'Rau, Indore', null, 'Residential Plot', 1800, '800 – 1,800 sq ft', 0, 0, 'Available', true, 'plot', null, 'P-IND-24-4705', null, null, '''Elegance redefined'' — residential plots designed with a natural light focus, ranging from 800 to 1,800 sq ft, minutes from IIM Indore at Rau.', '["Amphitheatre", "Water bodies", "Kids'' play area", "Jogging track", "Gazebo", "Open garden"]'::jsonb, null, 2),
  ('MRS-204', 'Emerald Forum', 'Indore', null, 'Commercial', 1600, 'Sizes on request', 0, 0, 'Available', true, 'office', null, 'P-IND-26-6485', null, null, '''Premium spaces for business'' — Emerald Forum is now RERA-approved. A glass-façade commercial tower of ground-floor showrooms and office floors lined with green planter balconies. Sizes and rates on request.', '["Ground-floor showrooms", "Office floors above retail", "Planter-lined green balconies", "By the Emerald group"]'::jsonb, null, 3),
  ('MRS-1206598', '2 BHK Apartment in Bhawrasla, Indore', 'Bhawrasla, Indore', null, 'Apartment', 1025, '1,025 sq ft', 2, 2, 'Available', false, 'towers', null, null, 'New Property', null, 'Well designed 2 BHK Flats & Apartments, 1150 Sq.ft. Built Up Area, is available for sale at Bhawrasla, Indore at a reasonable price of INR 58 Lac. This property highlights are several amenities like Power Back Up, Lift, Reserved Parking, Security, Maintenance Staff. This property has very basic…', '["Power Back Up", "Lift", "Reserved Parking", "Security", "Maintenance Staff"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1206598_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1206598_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 4),
  ('MRS-1472601', 'Apartment in Kanadia Road, Indore', 'Kanadia Road, Indore', 22500000, 'Apartment', 2438, '2,438 sq ft', 3, 0, 'Available', false, 'towers', 9229, null, 'New Property', 'East', 'Flats / Apartments is available for sale in Kanadia Road, Indore only in Rs. 2.25 Cr. This flat for sale has a prime location. This premium furnished 3 BHK Flats / Apartments spells quality and comfort at a competitive price under Rs. 2.25 Cr. Family friendly location with close proximity to…', '["Power Back Up", "Reserved Parking", "Security"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1472601_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1472601_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 5),
  ('MRS-1483796', '3 BHK Apartment in Kanadiya, Indore', 'Kanadiya, Indore', 24400000, 'Apartment', 2438, '2,438 sq ft', 3, 0, 'Available', false, 'towers', 10000, null, 'New Property', 'East', 'Located in the sought-after area of Kanadiya, Indore, this spacious 3 BHK flat offers a perfect blend of modern living and convenience. Situated on the 4th floor of a 21-storey building, this new property spans a generous 2438 sq. ft. The flat boasts an East-facing orientation, allowing for…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1483796_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1483796_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 6),
  ('MRS-1314393', 'Showrooms in Indrapuri Colony, Indore', 'Indrapuri Colony, Indore', 9200000, 'Commercial', 950, '950 sq ft', 0, 0, 'Available', false, 'office', 9684, null, 'New Property', null, 'A 950 sq ft showroom at Rajiv Gandhi Square, Indrapuri Colony — ground-floor frontage on the BRTS corridor, close to Choitram Square and Bhawarkua. Call for the floor plan and current rate.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1314393_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1314393_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 7),
  ('MRS-1197825', 'Unity One — office space at Rajiv Gandhi Square', 'Indrapuri Colony, Indore', 9000000, 'Commercial', 975, '975 sq ft built-up · 1,400 sq ft super', 0, 0, 'Available', true, 'office', 9231, 'P-IND-21-3082', null, null, 'A 975 sq ft office floor in Unity One — a seven-storey mixed-use tower at Rajiv Gandhi Square with three basement parking levels. Showrooms and shops occupy the ground and first floors, offices sit around an Origami garden on the second, and larger office plates run from the third to the sixth. On the BRTS corridor, 300 m from Choitram Square and 1.4 km from Bhawarkua Square.', '["Power Back Up", "Water Storage", "Five lifts with a spacious lobby", "Reserved Parking", "Security", "Maintenance Staff", "High-tech fire detection", "CCTV surveillance", "Dedicated electric substation"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1197825_3.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 8),
  ('MRS-1315219', 'Commercial Shops in Indrapuri Colony, Indore', 'Indrapuri Colony, Indore', 4000000, 'Commercial', 521, '521 sq ft', 0, 0, 'Available', false, 'office', 7678, null, 'New Property', null, 'Economic shop showroom & offices starting range 40,00,000', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, null, 9),
  ('MRS-1310596', 'Office Space in MR 10, Indore', 'MR 10, Indore', 6500000, 'Commercial', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'office', 6500, null, 'New Property', null, 'OFFICES for IT company INDORE Near MR 10 near ISBT connectivity ISBT, metro station, Airport, Indian Railways, Economic corridor', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1310596_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 10),
  ('MRS-1320748', 'Luxurious Offices 4 Ways Connectivity Near Metro Stations Isbt Proposal, Near Airport', 'MR 10, Indore', 4610000, 'Commercial', 0, 'Size on request', 0, 1, 'Available', false, 'office', 10000, null, 'New Property', null, 'Furnished Office Space in MR 10, Indore ready to use, available for sale at a very affordable price. Along with carpet area 361 Sq.ft.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1320748_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1320748_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 11),
  ('MRS-1311101', 'Commercial Land in Panchderiya, Indore', 'Panchderiya, Indore', 9000000, 'Commercial Land', 2000, '2,000 sq ft', 0, 0, 'Available', false, 'plot', 4500, null, 'New Property', null, 'Suitable 2000 Sq.ft. Commercial Plots is available for sale in the prime location of Panchderiya, Indore with all types of basic amenities and facilities in Rs. 90 Lac affordable rate for more please contact in given number. Commercial plot with comfort plot area 2000 sqft', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, null, 12),
  ('MRS-1494088', 'Commercial Land in Sula Khedi, Indore', 'Sula Khedi, Indore', 15400000, 'Commercial Land', 2200, '2,200 sq ft', 0, 0, 'Available', false, 'plot', 7000, null, 'New Property', null, 'Located in the bustling area of Sula Khedi, Indore, this spacious commercial land spans over 2200 sq.ft. and is ideal for various business ventures. Situated in a prime location, this new property is perfect for investors looking to establish their presence in a rapidly growing commercial hub.…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1494088_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1494088_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 13),
  ('MRS-1328170', 'Residential-cum-commercial land at Junarda Puwarda', 'Super Corridor, Indore', null, 'Commercial Land', 0, 'Size on request', 0, 0, 'Available', false, 'plot', null, null, 'New Property', null, 'Residential-cum-commercial land at Junarda Puwarda, close to the proposed Ahilya Path and fronting a 100 ft road. Connected to Palia, Ujjain Road, Hatod and TCS Square on the Super Corridor, with the railway station, metro line and airport all within reach.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1328170_4.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 14),
  ('MRS-1359342', 'Individual Houses in Mhow, Indore', 'Mhow, Indore', 8200000, 'Independent House', 2100, '2,100 sq ft', 3, 0, 'Available', false, 'villa', 3905, null, 'New Property', 'East', 'This attractive 3 BHK Independent House for sale Mhow, Indore. This ready to move House is sold at a fair selling price of Rs. 82 Lac. The Independent House is fully-furnished. This beautiful 3 BHK Independent House is area of 2100 Sq.ft.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, null, 15),
  ('MRS-1408421', '2 BHK Independent House in Sudama Nagar, Indore', 'Sudama Nagar, Indore', 13500000, 'Independent House', 925, '925 sq ft', 2, 2, 'Available', false, 'villa', 14595, null, 'Resale Property', 'West', '18*50 dismental house size Annapurna road k backside', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, null, 16),
  ('MRS-1352686', 'Individual Houses in Sudama Nagar, Indore', 'Sudama Nagar, Indore', 12200000, 'Independent House', 900, '900 sq ft', 3, 0, 'Available', false, 'villa', 13556, null, 'Resale Property', null, 'This attractive 3 BHK Independent House for sale Sudama Nagar, Indore. This ready to move House is sold at a fair selling price of Rs. 1.22 Cr. The Independent House is fully-furnished. This beautiful 3 BHK Independent House is area of 900 Sq.ft.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, null, 17),
  ('MRS-1496570', 'Residential Plot in Bada Bangarda, Indore', 'Bada Bangarda, Indore', 4600000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 4600, null, 'New Property', null, 'Located in the thriving city of Indore, this Residential Plot on Bada Bangarda is a prime investment opportunity. With a generous plot size of 1000 Sq.ft., this new property is perfect for building your dream home in a well-established neighborhood. Situated in a sought-after area, this plot…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1496570_7.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 18),
  ('MRS-1491204', 'Residential Plot in Bada Bangarda, Indore', 'Bada Bangarda, Indore', 3650000, 'Residential Plot', 800, '800 sq ft', 0, 0, 'Available', false, 'plot', 4563, null, 'Resale Property', null, 'Located in the prime location of Bada Bangarda in Indore, this 800 sq.ft. residential plot is now available for resale. Situated in a peaceful and well-connected neighborhood, this property offers the perfect opportunity to build your dream home in a desirable area. This freehold property is…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1491204_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1491204_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 19),
  ('MRS-1491432', 'Residential Plot in Bada Bangarda, Indore', 'Bada Bangarda, Indore', 3400000, 'Residential Plot', 750, '750 sq ft', 0, 0, 'Available', false, 'plot', 4533, null, 'Resale Property', null, 'The residential plot located in Bada Bangarda, Indore offers a prime location for those looking to build their dream home in a peaceful and conveniently located neighborhood. Situated on a 750 sq.ft. plot of land, this property is ideal for individuals or families seeking to customize their…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1491432_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 20),
  ('MRS-1486808', 'Residential Plot in By Pass Road, Indore', 'By Pass Road, Indore', 40000000, 'Residential Plot', 10000, '10,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, 'Located in the prime area of By Pass Road in Indore, this residential plot spans over 10,000 square feet and is ideal for those looking to build their dream home in a conveniently located and rapidly developing neighborhood. The plot is a new property and is being offered for sale on a freehold…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486808_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486808_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 21),
  ('MRS-1434898', 'Residential Plot in By Pass Road, Indore', 'By Pass Road, Indore', 35000000, 'Residential Plot', 10000, '10,000 sq ft', 0, 0, 'Available', false, 'plot', 3500, null, 'New Property', null, 'Exclusive! Residential Land / Plots for sale in By Pass Road, Indore. The land is available for sale at an affordable price of Rs. 3.50 Cr. Call & enjoy the freedom of space on this vast 10000 Sq.ft. plot located on By Pass Road, Indore.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1434898_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434898_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 22),
  ('MRS-1486807', 'Residential Plot in By Pass Road, Indore', 'By Pass Road, Indore', 32000000, 'Residential Plot', 8000, '8,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, 'Located on By Pass Road in Indore, this residential plot offers a prime opportunity for those looking to build their dream home in a bustling urban setting. With a spacious land area of 8000 sq.ft., this new property is available for sale on a freehold basis. Situated in a sought-after area of…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486807_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486807_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 23),
  ('MRS-1486811', 'Residential Plot in By Pass Road, Indore', 'By Pass Road, Indore', 16000000, 'Residential Plot', 4000, '4,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, 'Located on By Pass Road in Indore, this 4000 sq.ft. residential plot offers a great opportunity for those looking to build their dream home in a well-connected and rapidly developing area. The plot is part of a new property listing, making it a blank canvas for the buyer to design and construct…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486811_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486811_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 24),
  ('MRS-1439771', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 36000000, 'Residential Plot', 9000, '9,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 9,000 sq ft residential plot at Dewas Naka, Indore, available at ₹3.6 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439771_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 25),
  ('MRS-1439770', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 32000000, 'Residential Plot', 8000, '8,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 8,000 sq ft residential plot at Dewas Naka, Indore, available at ₹3.2 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439770_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 26),
  ('MRS-1439769', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 28000000, 'Residential Plot', 7000, '7,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 7,000 sq ft residential plot at Dewas Naka, Indore, available at ₹2.8 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439769_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 27),
  ('MRS-1439768', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 24000000, 'Residential Plot', 6000, '6,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 6,000 sq ft residential plot at Dewas Naka, Indore, available at ₹2.4 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439768_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 28),
  ('MRS-1439767', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 20000000, 'Residential Plot', 5000, '5,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 5,000 sq ft residential plot at Dewas Naka, Indore, available at ₹2 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439767_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 29),
  ('MRS-1439766', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 16000000, 'Residential Plot', 4000, '4,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 4,000 sq ft residential plot at Dewas Naka, Indore, available at ₹1.6 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439766_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 30),
  ('MRS-1439765', 'Residential Plot in Dewas Naka, Indore', 'Dewas Naka, Indore', 14000000, 'Residential Plot', 3500, '3,500 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, null, null, 'A 3,500 sq ft residential plot at Dewas Naka, Indore, available at ₹1.4 Cr (₹4,000/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439765_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 31),
  ('MRS-1434878', 'Residential Plot in Mayakhedi, Indore', 'Mayakhedi, Indore', 20000000, 'Residential Plot', 5000, '5,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, 'Exclusive! Residential Land / Plots for sale in Mayakhedi, Indore. The land is available for sale at an affordable price of Rs. 2 Cr. Call & enjoy the freedom of space on this vast 5000 Sq.ft. plot located on Mayakhedi, Indore.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1434878_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434878_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 32),
  ('MRS-1434093', 'Residential Plot in Mayakhedi, Indore', 'Mayakhedi, Indore', 16000000, 'Residential Plot', 4000, '4,000 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, '4000 Sq.ft. Residential Plots is available for sale well-located Residential Land / Plots in Mayakhedi, Indore. At a very affordable price. This Residential Land / Plots is located near a schools, hospitals, ATMs etc. Luxurious township rich look', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1434093_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434093_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 33),
  ('MRS-1434866', 'Residential Plot in Mayakhedi, Indore', 'Mayakhedi, Indore', 15200000, 'Residential Plot', 3800, '3,800 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, 'A Residential Land / Plots is available for sale at Mayakhedi, Indore. It is located in a very good area. The plot is measures 3800 Sq.ft. and priced Rs. 1.52 Cr. / negotiable will disclose after contact', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1434866_2.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_3.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_4.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_5.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_6.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_7.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_8.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_9.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1434866_10.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 34),
  ('MRS-1486728', 'Residential Plot in Mayakhedi, Indore', 'Mayakhedi, Indore', 14400000, 'Residential Plot', 1800, '1,800 sq ft', 0, 0, 'Available', false, 'plot', 8000, null, 'New Property', null, 'Located in the serene neighborhood of Mayakhedi in Indore, this residential plot spans 1800 square feet and is available for sale as a new property. The plot is freehold, ensuring that the new owner has complete ownership and rights over the land. The property is situated in a well-developed…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486728_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486728_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 35),
  ('MRS-1486726', 'Residential Plot in Mayakhedi, Indore', 'Mayakhedi, Indore', 12000000, 'Residential Plot', 1500, '1,500 sq ft', 0, 0, 'Available', false, 'plot', 8000, null, 'New Property', null, 'Located in the bustling city of Indore, this residential plot is situated in the peaceful neighborhood of Mayakhedi. With a land area of 1500 sq.ft., this new property is ideal for those looking to build their dream home in a prime location. The plot is freehold, providing the buyer with…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486726_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486726_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 36),
  ('MRS-1486632', 'Residential Plot in Mayakhedi, Indore', 'Mayakhedi, Indore', 9600000, 'Residential Plot', 1200, '1,200 sq ft', 0, 0, 'Available', false, 'plot', 8000, null, 'New Property', null, 'Nestled in the peaceful locality of Mayakhedi in Indore, this residential plot offers an excellent opportunity for anyone looking to build their dream home. With a land area of 1200 sq. ft., this new property is available for sale on a freehold basis. Located in a well-developed area, the plot…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486632_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486632_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 37),
  ('MRS-1492381', 'Residential Plot in Nainod, Indore', 'Nainod, Indore', 4200000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 4200, null, 'New Property', null, 'Located in the up-and-coming neighborhood of Nainod in Indore, this residential plot offers an ideal opportunity for those looking to build their dream home in a peaceful and well-connected area. With a land area of 1000 sq.ft., this new property is perfect for anyone looking to design and…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1492381_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492381_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492381_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492381_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492381_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492381_6.jpg", "fit": "cover", "label": "Photo 6"}]'::jsonb, 38),
  ('MRS-1195124', 'Residential Plot in Ujjain Road, Indore', 'Panchderiya, Indore', 8400000, 'Residential Plot', 800, '800 sq ft', 0, 0, 'Available', false, 'plot', 4200, null, null, null, 'A commercial Plot is available for sale pamchderia road, Ujjain Road, Indore. It is located in a very good area. The plot is measures 2000 Sq.ft. and priced 84,00,000 negotiable/ will disclose after contact This property has very basic facilities like School 2 Km.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1195124_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 39),
  ('MRS-1284243', 'Residential Plot in Panchderiya, Indore', 'Panchderiya, Indore', 3500000, 'Residential Plot', 2000, '2,000 sq ft', 0, 0, 'Available', false, 'plot', 3500, null, 'New Property', null, 'Residential plot with mazimum Amenities good connectivity', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1284243_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284243_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284243_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284243_4.jpg", "fit": "cover", "label": "Photo 4"}]'::jsonb, 40),
  ('MRS-1284116', 'Residential Plot in Panchderiya, Indore', 'Panchderiya, Indore', 2912000, 'Residential Plot', 850, '850 sq ft', 0, 0, 'Available', false, 'plot', 3425, null, 'New Property', null, 'Panchderiya near Universities good connectivity mangliya connectivity Ujjain road MR10 square connectivity', '["Reserved Parking", "Gymnasium", "Club House", "Maintenance Staff", "Vastu Compliant", "Swimming Pool"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1284116_7.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_8.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_9.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_10.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_11.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_12.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_13.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_14.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1284116_15.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 41),
  ('MRS-1357655', 'Residential Plot in Panchderiya, Indore', 'Panchderiya, Indore', 2400000, 'Residential Plot', 600, '600 sq ft', 0, 0, 'Available', false, 'plot', 4000, null, 'New Property', null, '600 Sq.ft. Residential Plots is available for sale well-located Residential Land / Plots in Panchderiya, Indore. At a very affordable price. This Residential Land / Plots is located near a schools, hospitals, ATMs etc.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1357655_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1357655_3.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1357655_4.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1357655_5.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1357655_6.jpg", "fit": "cover", "label": "Photo 5"}]'::jsonb, 42),
  ('MRS-1343724', 'Residential Plot in Panchderiya, Indore', 'Panchderiya, Indore', 2268000, 'Residential Plot', 600, '600 sq ft', 0, 0, 'Available', false, 'plot', 3780, null, 'New Property', null, 'This well-located Residential Land / Plots in a plot area of 600 Sq.ft. in Panchderiya, Indore is a beautiful green land. It is available on sale at a reasonable price of Rs. 22.68 Lac.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1343724_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 43),
  ('MRS-1486812', 'Residential Plot in Rau Pithampur Road, Indore', 'Rau Pithampur Road, Indore', 4750000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 4750, null, 'New Property', null, 'Located on the bustling Rau Pithampur Road in Indore, this residential plot offers a prime opportunity for those looking to build their dream home in a sought-after area. With a land area of 1000 sq.ft., this new property is perfect for those looking to design a custom living space tailored to…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486812_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486812_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 44),
  ('MRS-1422778', 'Residential Plot in Rau Pithampur Road, Indore', 'Rau Pithampur Road, Indore', 3200000, 'Residential Plot', 1500, '1,500 sq ft', 0, 0, 'Available', false, 'plot', 2133, null, 'New Property', null, 'Rau Pithampur Road near sanjay jhalashya near hotel manal investment mode peoperty', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1422778_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 45),
  ('MRS-1341348', 'Residential Plot in Rau Road, Indore', 'Rau Road, Indore', 9350000, 'Residential Plot', 1375, '1,375 sq ft', 0, 0, 'Available', false, 'plot', 6800, null, 'New Property', null, '1375 Sq.ft. Residential Plots is available for sale well-located Residential Land / Plots in Rau Road, Indore. At a very affordable price. This Residential Land / Plots is located near a schools, hospitals, ATMs etc.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1341348_2.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 46),
  ('MRS-1341352', 'Residential Plot in Rau, Indore', 'Rau, Indore', 9350000, 'Residential Plot', 1375, '1,375 sq ft', 0, 0, 'Available', false, 'plot', 6800, null, 'New Property', null, 'We have 1375 Sq.ft., Residential Land / Plots for sale. The land is a freehold, and would be suitable for your needs. The viewing address of this Residential Land / Plots on sale is Rau, Indore.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1341352_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1341352_3.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1341352_5.jpg", "fit": "cover", "label": "Photo 3"}]'::jsonb, 47),
  ('MRS-1492343', 'Residential Plot in Ringnodiya, Indore', 'Ringnodiya, Indore', 2900000, 'Residential Plot', 850, '850 sq ft', 0, 0, 'Available', false, 'plot', 3412, null, 'New Property', null, 'This 850 sq.ft. residential plot is located in a prime area, perfect for building your dream home. The property is a new development and is being offered for sale as a freehold. The plot is ideal for those looking to customize their home to their liking and create a space that suits their…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1492343_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1492343_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 48),
  ('MRS-1486906', 'Residential Plot in Sula Khedi, Indore', 'Sula Khedi, Indore', 9000000, 'Residential Plot', 1500, '1,500 sq ft', 0, 0, 'Available', false, 'plot', 6000, null, 'New Property', null, 'Located in the serene and developing area of Sula Khedi in Indore, this residential plot offers an excellent opportunity for those looking to build their dream home in a peaceful yet well-connected neighborhood. The plot spans 1500 sq.ft. and is being offered as a new property for sale on a…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486906_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486906_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486906_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486906_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486906_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486906_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486906_7.jpg", "fit": "cover", "label": "Photo 7"}]'::jsonb, 49),
  ('MRS-1486910', 'Residential Plot in Sula Khedi, Indore', 'Sula Khedi, Indore', 7200000, 'Residential Plot', 1200, '1,200 sq ft', 0, 0, 'Available', false, 'plot', 6000, null, 'New Property', null, 'Nestled in the serene suburb of Sula Khedi in Indore, this residential plot spans across 1200 square feet of freehold land, offering a remarkable opportunity for those looking to build their dream home in a peaceful and well-connected locality. Situated in a coveted residential area, the plot…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486910_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486910_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486910_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486910_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486910_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486910_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486910_7.jpg", "fit": "cover", "label": "Photo 7"}]'::jsonb, 50),
  ('MRS-1486899', 'Residential Plot in Sula Khedi, Indore', 'Sula Khedi, Indore', 6600000, 'Residential Plot', 1100, '1,100 sq ft', 0, 0, 'Available', false, 'plot', 6000, null, 'New Property', null, 'Located in the serene and peaceful neighborhood of Sula Khedi in Indore, this residential plot offers a perfect opportunity to build your dream home. The plot spans across 1100 square feet of freehold land, providing ample space for construction and landscaping. Situated in a well-established…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1486899_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486899_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486899_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486899_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486899_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486899_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1486899_7.jpg", "fit": "cover", "label": "Photo 7"}]'::jsonb, 51),
  ('MRS-1258076', 'Residential Plot in Super Corridor, Indore', 'Super Corridor, Indore', 4400000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 4400, null, 'New Property', null, 'Residential Land / Plots available at a reasonable price is a located in the prime area of Super Corridor, Indore. It has an area of 1000 Sq.ft. and very affordable priced at Rs. 32 Lac feel free to connect with us for price details. Super corridor 4.5 km away', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, null, 52),
  ('MRS-1415581', 'Residential Plot in Super Corridor, Indore', 'Super Corridor, Indore', 3400000, 'Residential Plot', 800, '800 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, 'Resale Property', null, 'This well-located Residential Land / Plots in a plot area of 800 Sq.ft. The land is available for sale in prime location at Super Corridor, Indore. In Residential Land / Plots point Indore is best location.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1415581_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415581_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415581_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415581_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415581_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415581_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415581_7.jpg", "fit": "cover", "label": "Photo 7"}]'::jsonb, 53),
  ('MRS-1415580', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 42500000, 'Residential Plot', 10000, '10,000 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, 'New Property', null, 'Cropped Residential Land / Plots for multipurpose use land are available at Ujjain Road, Indore, approx 10000 Sq.ft. Residential Land / Plots available for sale in best price Rs. 4.25 Cr. and essential for food production. Main ujjain Road Touch project', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1415580_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415580_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415580_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415580_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415580_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415580_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1415580_7.jpg", "fit": "cover", "label": "Photo 7"}]'::jsonb, 54),
  ('MRS-1439751', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 18000000, 'Residential Plot', 4235, '4,235 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 4,235 sq ft residential plot at Ujjain Road, Indore, available at ₹1.8 Cr (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439751_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 55),
  ('MRS-1395715', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 8350000, 'Residential Plot', 1500, '1,500 sq ft', 0, 0, 'Available', false, 'plot', 5567, null, null, null, 'Mitesh Real Estate has come up with a new Residential Property project Godrej Greenview Estate in Indore. The Residential Land / Plots size starts with 1500 Sq.ft. and have many more sizes. Located in one of the best Location of Indore', '["Club House", "Cafeteria", "CCTV Camera", "Gymnasium", "Intercom", "Indoor Games", "Jogging Track", "Kids Play Area", "Landspace Garden", "Meditation Area", "Power Back Up", "Park", "Play Area", "Reserved Parking", "Swimming Pool", "Security"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1395715_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395715_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395715_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395715_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395715_5.jpg", "fit": "cover", "label": "Photo 5"}]'::jsonb, 56),
  ('MRS-1395718', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 7250000, 'Residential Plot', 1250, '1,250 sq ft', 0, 0, 'Available', false, 'plot', 5800, null, null, null, 'Mitesh Real Estate has come up with a new Residential Property project Godrej Greenview Estate in Indore. The Residential Land / Plots size starts with 1250 Sq.ft. and have many more sizes. Located in one of the best Location of Indore', '["Club House", "Cafeteria", "CCTV Camera", "Gymnasium", "Intercom", "Indoor Games", "Jogging Track", "Kids Play Area", "Landspace Garden", "Meditation Area", "Power Back Up", "Park", "Play Area", "Reserved Parking", "Swimming Pool", "Security"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1395718_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395718_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395718_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395718_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395718_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395718_7.jpg", "fit": "cover", "label": "Photo 6"}]'::jsonb, 57),
  ('MRS-1395716', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 5550000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 5550, null, null, null, 'Mitesh Real Estate has come up with a new Residential Property project Godrej Greenview Estate in Indore. The Residential Land / Plots size starts with 1000 Sq.ft. and have many more sizes. Located in one of the best Location of Indore', '["Club House", "Cafeteria", "CCTV Camera", "Gymnasium", "Intercom", "Indoor Games", "Jogging Track", "Kids Play Area", "Landspace Garden", "Meditation Area", "Power Back Up", "Park", "Play Area", "Reserved Parking", "Swimming Pool", "Security"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1395716_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395716_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395716_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395716_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395716_5.jpg", "fit": "cover", "label": "Photo 5"}]'::jsonb, 58),
  ('MRS-1488128', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 5500000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 5500, null, 'New Property', null, 'Located in a prime area of Indore, this residential plot on Ujjain Road offers a great opportunity for those looking to build their dream home in a well-established neighborhood. With a plot size of 1000 sq.ft., this new property is ideal for those who value space and privacy. Situated in a…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1488128_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488128_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488128_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488128_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488128_5.jpg", "fit": "cover", "label": "Photo 5"}]'::jsonb, 59),
  ('MRS-1485121', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 4500000, 'Residential Plot', 1250, '1,250 sq ft', 0, 0, 'Available', false, 'plot', 3600, null, 'New Property', null, 'Located in the bustling city of Indore, this residential plot on Ujjain Road is a rare find in the real estate market. Spanning an area of 1250 sq.ft., this new property offers a blank canvas for you to build the home of your dreams. Situated in a prime location, this plot on Ujjain Road boasts…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1485121_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1485121_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 60),
  ('MRS-1439752', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 4488000, 'Residential Plot', 1056, '1,056 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 1,056 sq ft residential plot at Ujjain Road, Indore, available at ₹44.9 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439752_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 61),
  ('MRS-1488169', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 4400000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 4400, null, 'New Property', null, 'Located on the bustling Ujjain Road in Indore, this 1000 sq.ft. residential plot is a new property available for sale. The plot is perfect for anyone looking to build their dream home in a prime location with easy access to all necessary amenities. Situated in a desirable neighborhood, the…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1488169_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488169_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488169_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488169_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488169_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1488169_6.jpg", "fit": "cover", "label": "Photo 6"}]'::jsonb, 62),
  ('MRS-1480128', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 4250000, 'Residential Plot', 1000, '1,000 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, 'New Property', null, 'Located on Ujjain Road in the bustling city of Indore, this residential plot presents a unique opportunity for those seeking to build their dream home in a prime location. The 1000 sq. ft. plot is available for sale as a new property, offering a blank canvas for potential buyers to create a…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1480128_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_3.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_4.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_5.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_6.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_7.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_8.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1480128_9.jpg", "fit": "cover", "label": "Photo 8"}]'::jsonb, 63),
  ('MRS-1161758', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 4070000, 'Residential Plot', 1100, '1,100 sq ft', 0, 0, 'Available', false, 'plot', 3700, null, 'Resale Property', null, 'Prime location plot 40*60 2400 sqft corner plot suitable for residencial & commercial', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1161758_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 64),
  ('MRS-1439753', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 3778000, 'Residential Plot', 889, '889 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 889 sq ft residential plot at Ujjain Road, Indore, available at ₹37.8 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439753_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 65),
  ('MRS-1439759', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 3506000, 'Residential Plot', 825, '825 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 825 sq ft residential plot at Ujjain Road, Indore, available at ₹35.1 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439759_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 66),
  ('MRS-1439754', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 3264000, 'Residential Plot', 768, '768 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 768 sq ft residential plot at Ujjain Road, Indore, available at ₹32.6 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439754_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 67),
  ('MRS-1439755', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 3030000, 'Residential Plot', 713, '713 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 713 sq ft residential plot at Ujjain Road, Indore, available at ₹30.3 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439755_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 68),
  ('MRS-1439756', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 2988000, 'Residential Plot', 703, '703 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 703 sq ft residential plot at Ujjain Road, Indore, available at ₹29.9 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439756_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 69),
  ('MRS-1439757', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 2916000, 'Residential Plot', 686, '686 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 686 sq ft residential plot at Ujjain Road, Indore, available at ₹29.2 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439757_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 70),
  ('MRS-1439758', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 2720000, 'Residential Plot', 640, '640 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 640 sq ft residential plot at Ujjain Road, Indore, available at ₹27.2 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439758_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 71),
  ('MRS-1439760', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 1819000, 'Residential Plot', 428, '428 sq ft', 0, 0, 'Available', false, 'plot', 4250, null, null, null, 'A 428 sq ft residential plot at Ujjain Road, Indore, available at ₹18.2 Lakh (₹4,250/sq ft). Clear title and ready for registry — call to check current availability and arrange a site visit.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1439760_1.jpg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 72),
  ('MRS-1482765', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', 1637000, 'Residential Plot', 461, '461 sq ft', 0, 0, 'Available', false, 'plot', 3550, null, 'New Property', null, 'Located on Ujjain Road in Indore, this residential plot spans across 461 sq.ft. and is now available for sale. The property is a new development, offering a blank canvas for potential homeowners to design and build their dream home from scratch. This freehold plot is situated in a prime…', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1482765_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_5.jpg", "fit": "cover", "label": "Photo 5"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_6.jpg", "fit": "cover", "label": "Photo 6"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_7.jpg", "fit": "cover", "label": "Photo 7"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_8.jpg", "fit": "cover", "label": "Photo 8"}, {"src": "https://rei.wlimg.com/prop_images/884036/1482765_9.jpg", "fit": "cover", "label": "Photo 9"}]'::jsonb, 73),
  ('MRS-1195120', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', null, 'Residential Plot', 1800, '1,800 sq ft', 0, 0, 'Available', false, 'plot', null, null, null, null, '2000Sq.ft. Residential Plot available for sale at prime locatio of panchderiya road, Ujjain Road, Indore 84 Lac INR/ Interested person can send mail or cotact for more details.', '["Clear-title documentation", "Site visit arranged on a call", "Registry & loan guidance included"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1195120_1.jpeg", "fit": "cover", "label": "Photo 1"}]'::jsonb, 74),
  ('MRS-1395717', 'Residential Plot in Ujjain Road, Indore', 'Ujjain Road, Indore', null, 'Residential Plot', 2000, '2,000 sq ft', 0, 0, 'Available', false, 'plot', null, null, null, null, 'Mitesh Real Estate has come up with a new Residential Property project Godrej Greenview Estate in Indore. The Residential Land / Plots size starts with 2000 Sq.ft. and have many more sizes. Located in one of the best Location of Indore', '["Club House", "Cafeteria", "CCTV Camera", "Gymnasium", "Intercom", "Indoor Games", "Jogging Track", "Kids Play Area", "Landspace Garden", "Meditation Area", "Power Back Up", "Park", "Play Area", "Reserved Parking", "Swimming Pool", "Security"]'::jsonb, '[{"src": "https://rei.wlimg.com/prop_images/884036/1395717_1.jpg", "fit": "cover", "label": "Photo 1"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395717_2.jpg", "fit": "cover", "label": "Photo 2"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395717_3.jpg", "fit": "cover", "label": "Photo 3"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395717_4.jpg", "fit": "cover", "label": "Photo 4"}, {"src": "https://rei.wlimg.com/prop_images/884036/1395717_5.jpg", "fit": "cover", "label": "Photo 5"}]'::jsonb, 75);

-- Listings whose images stayed in code (data-URI creatives): the site falls back
-- to the bundled images for any row where images is null.

-- -------------------------------------------------------------- testimonials
-- Add real client reviews here — the carousel renders however many rows exist,
-- so it scales from 3 to 100 without any code change.
drop table if exists public.testimonials cascade;

create table public.testimonials (
  id         bigint generated always as identity primary key,
  name       text    not null,
  role       text,                       -- e.g. "Bought a 3 BHK in Vijay Nagar"
  rating     smallint not null default 5 check (rating between 1 and 5),
  text       text    not null,
  source     text,                       -- where the review came from (Google, WhatsApp, in person…)
  sort_order integer not null default 0,
  published  boolean not null default true,
  created_at timestamptz not null default now()
);

create index testimonials_sort_idx on public.testimonials (sort_order);

alter table public.testimonials enable row level security;

create policy "anon can read published testimonials"
  on public.testimonials for select to anon using (published);

-- No anon insert policy: reviews are added from the dashboard, so the section
-- cannot be filled with unverified submissions from the open internet.

insert into public.testimonials (name, role, rating, text, source, sort_order) values
  ('Rohit & Sneha Kulkarni', 'Bought a plot near Rau', 5, 'We had visited eleven layouts on our own and were exhausted. Mitesh ji shortlisted three, explained exactly why, and negotiated well below the quoted rate. Our registry was done before the possession date.', 'client', 0),
  ('राजेश पाटीदार', 'उज्जैन रोड पर प्लॉट खरीदा', 5, 'उज्जैन रोड पर प्लॉट लेना था, पर कागज़ों की समझ नहीं थी। मितेश जी ने रजिस्ट्री, नामांतरण और लोन तक सब खुद संभाला। रेट भी एकदम सही लगवाया — भरोसे का नाम है।', 'client', 1),
  ('Priya Sharma', 'Bought a plot on the Super Corridor', 5, 'As a first-time buyer I had a hundred questions. They answered every one patiently, showed me the T&CP approvals themselves, and never pushed me toward a bigger budget. My registry was done in three weeks.', 'client', 2),
  ('सुनीता व अनिल चौहान', 'एबी बायपास पर प्लॉट लिया', 5, 'हमें घर बनाने के लिए साफ़ टाइटल वाला प्लॉट चाहिए था। तीन लेआउट दिखाए और हर एक की कमी-खूबी साफ़ बताई। कहीं भी जल्दबाज़ी नहीं करवाई — आज हम पूरी तरह निश्चिंत हैं।', 'client', 3),
  ('Vikram Rathore', 'Commercial investor', 4, 'I compare every deal hard, and their rental and appreciation numbers were the most honest I heard in Indore. Took a commercial space through them and the possession paperwork was flawless.', 'client', 4),
  ('दीपक मालवीय', 'पिथमपुर रोड पर निवेश', 5, 'साइट विज़िट से लेकर रजिस्ट्री तक पूरा साथ दिया। RERA और T&CP के सारे कागज़ पहले ही जाँच कर दिखाए। यहाँ दलाली नहीं, सलाह मिलती है।', 'client', 5),
  ('अर्जुन यादव', 'देवास बायपास पर प्लॉट', 5, 'देवास बायपास पर तीन लेआउट दिखाए, हर प्लॉट का रेट और अप्रूवल खुलकर बताया। बिना किसी दबाव के फ़ैसला करने दिया — ऐसी ईमानदारी कम मिलती है।', 'client', 6),
  ('Kavita Verma', 'Bought a plot on AB Bypass', 4, 'They arranged site visits on a Sunday for our whole family, shared the layout map and rate list openly, and helped with the loan file too. Everything was done in one clean, transparent process.', 'client', 7),
  ('मनोज शर्मा', 'सुपर कॉरिडोर निवेशक', 5, 'निवेश के लिए सुपर कॉरिडोर चुनने में इन्होंने मेट्रो और आईटी बेल्ट का पूरा गणित समझाया। जो प्लॉट सही नहीं था, उसके लिए साफ़ मना भी किया। यही फ़र्क है सलाहकार और दलाल में।', 'client', 8),
  ('Amit & Pooja Dubey', 'Building a home at Rau', 5, 'From shortlisting the plot to the naamantaran after registry, one desk handled everything. Six months later they still pick up the phone for every small question. Highly recommended in Indore.', 'client', 9),
  ('मुकेश सोलंकी', 'सुला खेड़ी में प्लॉट बुक किया', 4, 'गेटवे की एंट्री देखकर ही मन बन गया था, पर मितेश जी ने पहले सारे अप्रूवल दिखाए, फिर बुकिंग करवाई। पैसों की पूरी पारदर्शिता — हर रसीद समय पर मिली।', 'client', 10),
  ('Dr. Nitin Vyas', 'Bought a plot at Mayakhedi, AB Bypass', 5, 'With hospital duties I had no time for paperwork. Their team collected documents from my clinic, completed the registry, and handed me the file with every approval in order. Completely hassle-free.', 'client', 11),
  ('सीमा सिसोदिया', 'पहली बार प्रॉपर्टी खरीदी', 5, 'अकेली महिला होने के नाते थोड़ी झिझक थी, पर यहाँ हर बात इज़्ज़त और धैर्य से समझाई गई। बजट से बाहर का प्लॉट दिखाया ही नहीं — यही बात सबसे अच्छी लगी।', 'client', 12),
  ('Ankit Agrawal', 'Investor · 3 plots via MRS', 5, 'I have bought three plots through them across the Ujjain Road and Pithampur belts. Rate history, layout comparisons, resale outlook — everything on paper before I pay a rupee. That discipline is rare.', 'client', 13),
  ('रमेशचंद्र जोशी', 'रिटायरमेंट के बाद प्लॉट लिया', 5, 'पेंशन की जमा-पूँजी थी, इसलिए सौ बार सोच रहा था। इन्होंने बेटे की तरह सलाह दी, दो किफ़ायती विकल्प खुद बताए और रजिस्ट्री तक साथ खड़े रहे। भगवान भला करे।', 'client', 14),
  ('Shraddha & Gaurav Tiwari', 'Plot near Rau for our first home', 4, 'We compared six dealers before choosing MRS. Only they showed us the actual T&CP map and walked the plot boundary with us. Booking to registry took 26 days flat.', 'client', 15),
  ('विनोद कुशवाह', 'देवास बायपास पर निवेश', 4, 'प्लॉट और पेपर वर्क दोनों बढ़िया। बस साइट विज़िट के लिए एक हफ़्ते इंतज़ार करना पड़ा क्योंकि डिमांड बहुत है। बाकी सेवा में कोई कमी नहीं।', 'client', 16),
  ('CA Rohini Khandelwal', 'Commercial space enquiry', 5, 'As a CA I audit every claim. Their yield calculations for the commercial project matched the market data I verified independently. Refreshingly honest numbers in this industry.', 'client', 17),
  ('ओमप्रकाश पटेल', 'उज्जैन रोड पर प्लॉट', 4, 'गाँव से आकर शहर में ज़मीन लेना आसान नहीं था। इन्होंने नक्शा, नामांतरण, डायवर्सन — सब सरल भाषा में समझाया और पूरा काम खुद करवाया।', 'client', 18),
  ('Neha Saxena', 'Bought remotely from Bangalore', 5, 'I did the entire Super Corridor purchase from Bangalore — video site visits, documents on email, registry through my father. Updates came on WhatsApp at every step. Felt completely safe.', 'client', 19),
  ('संजय परमार', 'पिथमपुर रोड पर प्लॉट', 4, 'फ़ैक्टरी पिथमपुर में है तो पास ही प्लॉट चाहिए था। तीन दिन में चार लेआउट दिखाए, रेट की तुलना करके सबसे सही सौदा करवाया। सीधा और साफ़ काम।', 'client', 20),
  ('Harsh & Payal Mishra', 'Plot at Sula Khedi', 5, 'The gateway project photos looked too good to be true, so we visited unannounced. The site matched the promise. MRS handled our home-loan file too — sanctioned in twelve days.', 'client', 21),
  ('कैलाश नागर', 'अपना प्लॉट बिकवाया', 5, 'मेरा पुराना प्लॉट डेढ़ महीने में सही दाम पर बिकवा दिया। ख़रीदार भी जाँचे-परखे लाए, और रजिस्ट्री वाले दिन तक पूरा साथ दिया। बेचने वालों के लिए भी उतने ही भरोसेमंद।', 'client', 22),
  ('Aditya Thakur', 'First-time buyer, Dewas Bypass', 4, 'Good guidance and genuine layouts. I would have liked more photos on WhatsApp before my first visit, but once on site, everything was exactly as described. Registry support was excellent.', 'client', 23),
  ('वंदना त्रिवेदी', 'एबी बायपास पर प्लॉट', 5, 'वास्तु के हिसाब से पूर्वमुखी प्लॉट चाहिए था। बिना झुंझलाए आठ प्लॉट दिखाए और आख़िर में वही दिलवाया जो हमें चाहिए था। धैर्य और समझ दोनों हैं इनमें।', 'client', 24),
  ('Er. Sachin Chaturvedi', 'Site engineer · bought at Rau', 4, 'I checked the internal road width, drainage lines and boundary markings myself — all as per the sanctioned layout. When an engineer cannot find faults, that says enough.', 'client', 25),
  ('मीना व राजेंद्र गौर', 'बेटी के भविष्य के लिए निवेश', 5, 'पाँच साल का नज़रिया रखकर प्लॉट लिया है। इन्होंने ग्रोथ वाले इलाक़े गिनकर बताए और काग़ज़ पक्के करवाए। अब निश्चिंत हैं कि सही जगह पैसा लगा है।', 'client', 26),
  ('Pankaj Panwar', 'Plot on Ujjain Road', 4, 'Booked during a Sunday site-visit camp. The rate list was printed and public — no whisper pricing, no special-discount drama. Straightforward dealing from start to finish.', 'client', 27),
  ('स्वाति पांडे', 'सुपर कॉरिडोर पर प्लॉट', 4, 'प्लॉट, पेपर और सर्विस — तीनों अच्छे। रजिस्ट्री की तारीख़ एक बार आगे बढ़ी थी, पर वजह पहले ही बता दी गई थी। ईमानदारी से काम करने वाली टीम।', 'client', 28),
  ('Mahesh & Sushila Choudhary', 'Built our retirement home at Rau', 5, 'Two years ago they helped us buy the plot; this year they connected us to a reliable contractor and even came for the griha pravesh. That is not business, that is relationship.', 'client', 29);

-- ------------------------------------------------------------- inbox view
-- Convenience view for reading leads in the dashboard: resolves property_id to
-- the listing title and shows IST timestamps.
--
-- security_invoker makes the view respect the caller's RLS. Without it a view
-- runs with its owner's rights, and anon could read every lead straight through
-- it — bypassing the policy on the underlying table.
create or replace view public.enquiries_inbox
with (security_invoker = true) as
select e.id,
       e.created_at at time zone 'Asia/Kolkata' as received_ist,
       e.handled,
       e.ref,
       e.name,
       e.phone,
       e.email,
       coalesce(p.title, e.property_id, '—') as enquired_about,
       p.location,
       e.budget,
       e.location as preferred_area,
       e.message
from public.enquiries e
left join public.properties p on p.id = e.property_id
order by e.created_at desc;
